import os
import numpy as np
import tempfile, zipfile
import torch
import torch.nn as nn
import torch.nn.functional as F
try:
    import torchvision
    import torchaudio
except:
    pass

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_Conv1_Conv2D_1 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=3, kernel_size=(3,3), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(2,2))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_Conv1_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_expanded_conv_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_expanded_conv_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_expanded_conv_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=16, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=16, kernel_size=(1,1), out_channels=96, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_depthwise_depthwise_1 = nn.Conv2d(bias=True, dilation=(1,1), groups=96, in_channels=96, kernel_size=(3,3), out_channels=96, padding=(0,0), padding_mode='zeros', stride=(2,2))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=24, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=24, kernel_size=(1,1), out_channels=144, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=144, in_channels=144, kernel_size=(3,3), out_channels=144, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=144, kernel_size=(1,1), out_channels=24, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=24, kernel_size=(1,1), out_channels=144, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=144, in_channels=144, kernel_size=(3,3), out_channels=144, padding=(1,1), padding_mode='zeros', stride=(2,2))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=144, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=192, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=192, in_channels=192, kernel_size=(3,3), out_channels=192, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=192, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=192, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=192, in_channels=192, kernel_size=(3,3), out_channels=192, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=192, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=192, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_depthwise_depthwise_1 = nn.Conv2d(bias=True, dilation=(1,1), groups=192, in_channels=192, kernel_size=(3,3), out_channels=192, padding=(0,0), padding_mode='zeros', stride=(2,2))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=192, kernel_size=(1,1), out_channels=64, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=384, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=384, in_channels=384, kernel_size=(3,3), out_channels=384, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=384, kernel_size=(1,1), out_channels=64, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=384, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=384, in_channels=384, kernel_size=(3,3), out_channels=384, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=384, kernel_size=(1,1), out_channels=64, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=384, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=384, in_channels=384, kernel_size=(3,3), out_channels=384, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=384, kernel_size=(1,1), out_channels=64, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=384, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=384, in_channels=384, kernel_size=(3,3), out_channels=384, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=384, kernel_size=(1,1), out_channels=96, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=576, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=576, in_channels=576, kernel_size=(3,3), out_channels=576, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=576, kernel_size=(1,1), out_channels=96, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=576, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=576, in_channels=576, kernel_size=(3,3), out_channels=576, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=576, kernel_size=(1,1), out_channels=96, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=576, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=576, in_channels=576, kernel_size=(3,3), out_channels=576, padding=(1,1), padding_mode='zeros', stride=(2,2))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_0_ClassPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=576, kernel_size=(1,1), out_channels=273, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_0_BoxEncodingPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=576, kernel_size=(1,1), out_channels=12, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=576, kernel_size=(1,1), out_channels=160, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=160, kernel_size=(1,1), out_channels=960, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=960, in_channels=960, kernel_size=(3,3), out_channels=960, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=960, kernel_size=(1,1), out_channels=160, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=160, kernel_size=(1,1), out_channels=960, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=960, in_channels=960, kernel_size=(3,3), out_channels=960, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=960, kernel_size=(1,1), out_channels=160, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_expand_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=160, kernel_size=(1,1), out_channels=960, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_expand_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_depthwise_depthwise = nn.Conv2d(bias=True, dilation=(1,1), groups=960, in_channels=960, kernel_size=(3,3), out_channels=960, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_depthwise_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_project_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=960, kernel_size=(1,1), out_channels=320, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_Conv_1_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=320, kernel_size=(1,1), out_channels=1280, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_out_relu_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_2_1x1_256_conv_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=1280, kernel_size=(1,1), out_channels=256, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_1_ClassPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=1280, kernel_size=(1,1), out_channels=546, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_1_BoxEncodingPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=1280, kernel_size=(1,1), out_channels=24, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_2_1x1_256_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_2_3x3_s2_512_conv_Conv2D_1 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=256, kernel_size=(3,3), out_channels=512, padding=(0,0), padding_mode='zeros', stride=(2,2))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_2_3x3_s2_512_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_3_1x1_128_conv_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=512, kernel_size=(1,1), out_channels=128, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_2_ClassPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=512, kernel_size=(1,1), out_channels=546, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_2_BoxEncodingPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=512, kernel_size=(1,1), out_channels=24, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_3_1x1_128_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_3_3x3_s2_256_conv_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=128, kernel_size=(3,3), out_channels=256, padding=(1,1), padding_mode='zeros', stride=(2,2))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_3_3x3_s2_256_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_4_1x1_128_conv_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=256, kernel_size=(1,1), out_channels=128, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_3_ClassPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=256, kernel_size=(1,1), out_channels=546, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_3_BoxEncodingPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=256, kernel_size=(1,1), out_channels=24, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_4_1x1_128_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_4_3x3_s2_256_conv_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=128, kernel_size=(3,3), out_channels=256, padding=(1,1), padding_mode='zeros', stride=(2,2))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_4_3x3_s2_256_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_5_1x1_64_conv_Conv2D = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=256, kernel_size=(1,1), out_channels=64, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_4_ClassPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=256, kernel_size=(1,1), out_channels=546, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_4_BoxEncodingPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=256, kernel_size=(1,1), out_channels=24, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_5_1x1_64_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_conv_Conv2D_1 = nn.Conv2d(bias=False, dilation=(1,1), groups=1, in_channels=64, kernel_size=(3,3), out_channels=128, padding=(0,0), padding_mode='zeros', stride=(2,2))
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_batchnorm_FusedBatchNormV3 = nn.BatchNorm2d(affine=True, eps=0.001, num_features=128)
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_Relu6 = nn.ReLU6()
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_5_ClassPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=128, kernel_size=(1,1), out_channels=546, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_5_BoxEncodingPredictor_BiasAdd = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=128, kernel_size=(1,1), out_channels=24, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.core_StatefulPartitionedCall_Postprocessor_convert_scores = nn.Sigmoid()

        archive = zipfile.ZipFile('ssd_try_pnnx.pnnx.bin', 'r')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_Conv1_Conv2D_1.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/Conv1/Conv2D.1.bias', (32), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_Conv1_Conv2D_1.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/Conv1/Conv2D.1.weight', (32,3,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_expanded_conv_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/expanded_conv_depthwise/depthwise.bias', (32), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_expanded_conv_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/expanded_conv_depthwise/depthwise.weight', (32,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_expanded_conv_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/expanded_conv_project/Conv2D.bias', (16), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_expanded_conv_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/expanded_conv_project/Conv2D.weight', (16,32,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_1_expand/Conv2D.bias', (96), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_1_expand/Conv2D.weight', (96,16,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_depthwise_depthwise_1.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_1_depthwise/depthwise.1.bias', (96), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_depthwise_depthwise_1.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_1_depthwise/depthwise.1.weight', (96,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_1_project/Conv2D.bias', (24), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_1_project/Conv2D.weight', (24,96,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_2_expand/Conv2D.bias', (144), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_2_expand/Conv2D.weight', (144,24,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_2_depthwise/depthwise.bias', (144), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_2_depthwise/depthwise.weight', (144,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_2_project/Conv2D.bias', (24), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_2_project/Conv2D.weight', (24,144,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_3_expand/Conv2D.bias', (144), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_3_expand/Conv2D.weight', (144,24,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_3_depthwise/depthwise.bias', (144), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_3_depthwise/depthwise.weight', (144,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_3_project/Conv2D.bias', (32), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_3_project/Conv2D.weight', (32,144,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_4_expand/Conv2D.bias', (192), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_4_expand/Conv2D.weight', (192,32,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_4_depthwise/depthwise.bias', (192), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_4_depthwise/depthwise.weight', (192,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_4_project/Conv2D.bias', (32), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_4_project/Conv2D.weight', (32,192,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_5_expand/Conv2D.bias', (192), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_5_expand/Conv2D.weight', (192,32,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_5_depthwise/depthwise.bias', (192), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_5_depthwise/depthwise.weight', (192,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_5_project/Conv2D.bias', (32), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_5_project/Conv2D.weight', (32,192,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_6_expand/Conv2D.bias', (192), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_6_expand/Conv2D.weight', (192,32,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_depthwise_depthwise_1.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_6_depthwise/depthwise.1.bias', (192), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_depthwise_depthwise_1.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_6_depthwise/depthwise.1.weight', (192,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_6_project/Conv2D.bias', (64), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_6_project/Conv2D.weight', (64,192,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_7_expand/Conv2D.bias', (384), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_7_expand/Conv2D.weight', (384,64,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_7_depthwise/depthwise.bias', (384), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_7_depthwise/depthwise.weight', (384,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_7_project/Conv2D.bias', (64), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_7_project/Conv2D.weight', (64,384,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_8_expand/Conv2D.bias', (384), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_8_expand/Conv2D.weight', (384,64,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_8_depthwise/depthwise.bias', (384), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_8_depthwise/depthwise.weight', (384,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_8_project/Conv2D.bias', (64), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_8_project/Conv2D.weight', (64,384,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_9_expand/Conv2D.bias', (384), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_9_expand/Conv2D.weight', (384,64,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_9_depthwise/depthwise.bias', (384), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_9_depthwise/depthwise.weight', (384,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_9_project/Conv2D.bias', (64), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_9_project/Conv2D.weight', (64,384,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_10_expand/Conv2D.bias', (384), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_10_expand/Conv2D.weight', (384,64,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_10_depthwise/depthwise.bias', (384), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_10_depthwise/depthwise.weight', (384,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_10_project/Conv2D.bias', (96), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_10_project/Conv2D.weight', (96,384,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_11_expand/Conv2D.bias', (576), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_11_expand/Conv2D.weight', (576,96,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_11_depthwise/depthwise.bias', (576), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_11_depthwise/depthwise.weight', (576,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_11_project/Conv2D.bias', (96), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_11_project/Conv2D.weight', (96,576,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_12_expand/Conv2D.bias', (576), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_12_expand/Conv2D.weight', (576,96,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_12_depthwise/depthwise.bias', (576), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_12_depthwise/depthwise.weight', (576,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_12_project/Conv2D.bias', (96), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_12_project/Conv2D.weight', (96,576,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_13_expand/Conv2D.bias', (576), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_13_expand/Conv2D.weight', (576,96,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_13_depthwise/depthwise.bias', (576), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_13_depthwise/depthwise.weight', (576,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_0_ClassPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_0/ClassPredictor/BiasAdd.bias', (273), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_0_ClassPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_0/ClassPredictor/BiasAdd.weight', (273,576,1,1), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_0_BoxEncodingPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_0/BoxEncodingPredictor/BiasAdd.bias', (12), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_0_BoxEncodingPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_0/BoxEncodingPredictor/BiasAdd.weight', (12,576,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_13_project/Conv2D.bias', (160), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_13_project/Conv2D.weight', (160,576,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_14_expand/Conv2D.bias', (960), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_14_expand/Conv2D.weight', (960,160,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_14_depthwise/depthwise.bias', (960), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_14_depthwise/depthwise.weight', (960,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_14_project/Conv2D.bias', (160), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_14_project/Conv2D.weight', (160,960,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_15_expand/Conv2D.bias', (960), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_15_expand/Conv2D.weight', (960,160,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_15_depthwise/depthwise.bias', (960), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_15_depthwise/depthwise.weight', (960,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_15_project/Conv2D.bias', (160), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_15_project/Conv2D.weight', (160,960,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_expand_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_16_expand/Conv2D.bias', (960), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_expand_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_16_expand/Conv2D.weight', (960,160,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_depthwise_depthwise.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_16_depthwise/depthwise.bias', (960), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_depthwise_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_16_depthwise/depthwise.weight', (960,1,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_project_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_16_project/Conv2D.bias', (320), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_project_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/block_16_project/Conv2D.weight', (320,960,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_Conv_1_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/Conv_1/Conv2D.bias', (1280), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_Conv_1_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/functional_1/Conv_1/Conv2D.weight', (1280,320,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_2_1x1_256_conv_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_1_Conv2d_2_1x1_256_conv/Conv2D.bias', (256), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_2_1x1_256_conv_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_1_Conv2d_2_1x1_256_conv/Conv2D.weight', (256,1280,1,1), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_1_ClassPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_1/ClassPredictor/BiasAdd.bias', (546), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_1_ClassPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_1/ClassPredictor/BiasAdd.weight', (546,1280,1,1), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_1_BoxEncodingPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_1/BoxEncodingPredictor/BiasAdd.bias', (24), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_1_BoxEncodingPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_1/BoxEncodingPredictor/BiasAdd.weight', (24,1280,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_2_3x3_s2_512_conv_Conv2D_1.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_2_3x3_s2_512_conv/Conv2D.1.bias', (512), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_2_3x3_s2_512_conv_Conv2D_1.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_2_3x3_s2_512_conv/Conv2D.1.weight', (512,256,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_3_1x1_128_conv_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_1_Conv2d_3_1x1_128_conv/Conv2D.bias', (128), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_3_1x1_128_conv_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_1_Conv2d_3_1x1_128_conv/Conv2D.weight', (128,512,1,1), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_2_ClassPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_2/ClassPredictor/BiasAdd.bias', (546), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_2_ClassPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_2/ClassPredictor/BiasAdd.weight', (546,512,1,1), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_2_BoxEncodingPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_2/BoxEncodingPredictor/BiasAdd.bias', (24), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_2_BoxEncodingPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_2/BoxEncodingPredictor/BiasAdd.weight', (24,512,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_3_3x3_s2_256_conv_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_3_3x3_s2_256_conv/Conv2D.bias', (256), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_3_3x3_s2_256_conv_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_3_3x3_s2_256_conv/Conv2D.weight', (256,128,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_4_1x1_128_conv_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_1_Conv2d_4_1x1_128_conv/Conv2D.bias', (128), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_4_1x1_128_conv_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_1_Conv2d_4_1x1_128_conv/Conv2D.weight', (128,256,1,1), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_3_ClassPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_3/ClassPredictor/BiasAdd.bias', (546), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_3_ClassPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_3/ClassPredictor/BiasAdd.weight', (546,256,1,1), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_3_BoxEncodingPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_3/BoxEncodingPredictor/BiasAdd.bias', (24), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_3_BoxEncodingPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_3/BoxEncodingPredictor/BiasAdd.weight', (24,256,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_4_3x3_s2_256_conv_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_4_3x3_s2_256_conv/Conv2D.bias', (256), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_4_3x3_s2_256_conv_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_4_3x3_s2_256_conv/Conv2D.weight', (256,128,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_5_1x1_64_conv_Conv2D.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_1_Conv2d_5_1x1_64_conv/Conv2D.bias', (64), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_5_1x1_64_conv_Conv2D.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_1_Conv2d_5_1x1_64_conv/Conv2D.weight', (64,256,1,1), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_4_ClassPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_4/ClassPredictor/BiasAdd.bias', (546), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_4_ClassPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_4/ClassPredictor/BiasAdd.weight', (546,256,1,1), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_4_BoxEncodingPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_4/BoxEncodingPredictor/BiasAdd.bias', (24), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_4_BoxEncodingPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_4/BoxEncodingPredictor/BiasAdd.weight', (24,256,1,1), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_conv_Conv2D_1.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_5_3x3_s2_128_conv/Conv2D.1.weight', (128,64,3,3), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_batchnorm_FusedBatchNormV3.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_5_3x3_s2_128_batchnorm/FusedBatchNormV3.bias', (128), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_batchnorm_FusedBatchNormV3.running_mean = self.load_pnnx_bin_as_tensor(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_5_3x3_s2_128_batchnorm/FusedBatchNormV3.running_mean', (128), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_batchnorm_FusedBatchNormV3.running_var = self.load_pnnx_bin_as_tensor(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_5_3x3_s2_128_batchnorm/FusedBatchNormV3.running_var', (128), 'float32')
        self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_batchnorm_FusedBatchNormV3.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_5_3x3_s2_128_batchnorm/FusedBatchNormV3.weight', (128), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_5_ClassPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_5/ClassPredictor/BiasAdd.bias', (546), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_5_ClassPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalClassHead_5/ClassPredictor/BiasAdd.weight', (546,128,1,1), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_5_BoxEncodingPredictor_BiasAdd.bias = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_5/BoxEncodingPredictor/BiasAdd.bias', (24), 'float32')
        self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_5_BoxEncodingPredictor_BiasAdd.weight = self.load_pnnx_bin_as_parameter(archive, 'core.StatefulPartitionedCall/BoxPredictor/ConvolutionalBoxHead_5/BoxEncodingPredictor/BiasAdd.weight', (24,128,1,1), 'float32')
        self.pnnx_unique_2_data = self.load_pnnx_bin_as_parameter(archive, 'pnnx_unique_2.data', (1917,), 'float32')
        self.pnnx_unique_3_data = self.load_pnnx_bin_as_parameter(archive, 'pnnx_unique_3.data', (1917,), 'float32')
        self.pnnx_unique_4_data = self.load_pnnx_bin_as_parameter(archive, 'pnnx_unique_4.data', (1917,), 'float32')
        self.pnnx_unique_5_data = self.load_pnnx_bin_as_parameter(archive, 'pnnx_unique_5.data', (1917,), 'float32')
        self.pnnx_unique_6_data = self.load_pnnx_bin_as_parameter(archive, 'pnnx_unique_6.data', (1917,), 'float32')
        self.pnnx_unique_7_data = self.load_pnnx_bin_as_parameter(archive, 'pnnx_unique_7.data', (1917,), 'float32')
        archive.close()

    def load_pnnx_bin_as_parameter(self, archive, key, shape, dtype, requires_grad=True):
        return nn.Parameter(self.load_pnnx_bin_as_tensor(archive, key, shape, dtype), requires_grad)

    def load_pnnx_bin_as_tensor(self, archive, key, shape, dtype):
        fd, tmppath = tempfile.mkstemp()
        with os.fdopen(fd, 'wb') as tmpf, archive.open(key) as keyfile:
            tmpf.write(keyfile.read())
        m = np.memmap(tmppath, dtype=dtype, mode='r', shape=shape).copy()
        os.remove(tmppath)
        return torch.from_numpy(m)

    def forward(self, v_0):
        v_1 = v_0.permute(dims=(0,2,3,1))
        v_2 = self.pnnx_unique_2_data
        v_3 = self.pnnx_unique_3_data
        v_4 = self.pnnx_unique_4_data
        v_5 = self.pnnx_unique_5_data
        v_6 = self.pnnx_unique_6_data
        v_7 = self.pnnx_unique_7_data
        v_8 = ((0.00784314 * v_1) - 1.0)
        v_9 = torch.split(tensor=v_8, dim=0, split_size_or_sections=1)
        v_10 = v_9.permute(dims=(0,3,1,2))
        v_11 = F.upsample(v_10, align_corners=False, mode='bilinear', size=(300,300))
        v_12 = F.pad(v_11, mode='constant', pad=(0,1,0,1), value=0.0)
        v_13 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_Conv1_Conv2D_1(v_12)
        v_14 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_Conv1_relu_Relu6(v_13)
        v_15 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_expanded_conv_depthwise_depthwise(v_14)
        v_16 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_expanded_conv_depthwise_relu_Relu6(v_15)
        v_17 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_expanded_conv_project_Conv2D(v_16)
        v_18 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_expand_Conv2D(v_17)
        v_19 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_expand_relu_Relu6(v_18)
        v_20 = F.pad(v_19, mode='constant', pad=(0,1,0,1), value=0.0)
        v_21 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_depthwise_depthwise_1(v_20)
        v_22 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_depthwise_relu_Relu6(v_21)
        v_23 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_1_project_Conv2D(v_22)
        v_24 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_expand_Conv2D(v_23)
        v_25 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_expand_relu_Relu6(v_24)
        v_26 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_depthwise_depthwise(v_25)
        v_27 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_depthwise_relu_Relu6(v_26)
        v_28 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_2_project_Conv2D(v_27)
        v_29 = (v_23 + v_28)
        v_30 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_expand_Conv2D(v_29)
        v_31 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_expand_relu_Relu6(v_30)
        v_32 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_depthwise_depthwise(v_31)
        v_33 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_depthwise_relu_Relu6(v_32)
        v_34 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_3_project_Conv2D(v_33)
        v_35 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_expand_Conv2D(v_34)
        v_36 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_expand_relu_Relu6(v_35)
        v_37 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_depthwise_depthwise(v_36)
        v_38 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_depthwise_relu_Relu6(v_37)
        v_39 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_4_project_Conv2D(v_38)
        v_40 = (v_34 + v_39)
        v_41 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_expand_Conv2D(v_40)
        v_42 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_expand_relu_Relu6(v_41)
        v_43 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_depthwise_depthwise(v_42)
        v_44 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_depthwise_relu_Relu6(v_43)
        v_45 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_5_project_Conv2D(v_44)
        v_46 = (v_40 + v_45)
        v_47 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_expand_Conv2D(v_46)
        v_48 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_expand_relu_Relu6(v_47)
        v_49 = F.pad(v_48, mode='constant', pad=(0,1,0,1), value=0.0)
        v_50 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_depthwise_depthwise_1(v_49)
        v_51 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_depthwise_relu_Relu6(v_50)
        v_52 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_6_project_Conv2D(v_51)
        v_53 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_expand_Conv2D(v_52)
        v_54 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_expand_relu_Relu6(v_53)
        v_55 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_depthwise_depthwise(v_54)
        v_56 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_depthwise_relu_Relu6(v_55)
        v_57 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_7_project_Conv2D(v_56)
        v_58 = (v_52 + v_57)
        v_59 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_expand_Conv2D(v_58)
        v_60 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_expand_relu_Relu6(v_59)
        v_61 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_depthwise_depthwise(v_60)
        v_62 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_depthwise_relu_Relu6(v_61)
        v_63 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_8_project_Conv2D(v_62)
        v_64 = (v_58 + v_63)
        v_65 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_expand_Conv2D(v_64)
        v_66 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_expand_relu_Relu6(v_65)
        v_67 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_depthwise_depthwise(v_66)
        v_68 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_depthwise_relu_Relu6(v_67)
        v_69 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_9_project_Conv2D(v_68)
        v_70 = (v_64 + v_69)
        v_71 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_expand_Conv2D(v_70)
        v_72 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_expand_relu_Relu6(v_71)
        v_73 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_depthwise_depthwise(v_72)
        v_74 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_depthwise_relu_Relu6(v_73)
        v_75 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_10_project_Conv2D(v_74)
        v_76 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_expand_Conv2D(v_75)
        v_77 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_expand_relu_Relu6(v_76)
        v_78 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_depthwise_depthwise(v_77)
        v_79 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_depthwise_relu_Relu6(v_78)
        v_80 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_11_project_Conv2D(v_79)
        v_81 = (v_75 + v_80)
        v_82 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_expand_Conv2D(v_81)
        v_83 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_expand_relu_Relu6(v_82)
        v_84 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_depthwise_depthwise(v_83)
        v_85 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_depthwise_relu_Relu6(v_84)
        v_86 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_12_project_Conv2D(v_85)
        v_87 = (v_81 + v_86)
        v_88 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_expand_Conv2D(v_87)
        v_89 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_expand_relu_Relu6(v_88)
        v_90 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_depthwise_depthwise(v_89)
        v_91 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_0_ClassPredictor_BiasAdd(v_89)
        v_92 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_0_BoxEncodingPredictor_BiasAdd(v_89)
        v_93 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_depthwise_relu_Relu6(v_90)
        v_94 = v_91.permute(dims=(0,2,3,1))
        v_95 = v_92.permute(dims=(0,2,3,1))
        v_96 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_13_project_Conv2D(v_93)
        v_97 = v_94.reshape(1, 1083, 91)
        v_98 = v_95.reshape(1, 1083, 1, 4)
        v_99 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_expand_Conv2D(v_96)
        v_100 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_expand_relu_Relu6(v_99)
        v_101 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_depthwise_depthwise(v_100)
        v_102 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_depthwise_relu_Relu6(v_101)
        v_103 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_14_project_Conv2D(v_102)
        v_104 = (v_96 + v_103)
        v_105 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_expand_Conv2D(v_104)
        v_106 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_expand_relu_Relu6(v_105)
        v_107 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_depthwise_depthwise(v_106)
        v_108 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_depthwise_relu_Relu6(v_107)
        v_109 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_15_project_Conv2D(v_108)
        v_110 = (v_104 + v_109)
        v_111 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_expand_Conv2D(v_110)
        v_112 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_expand_relu_Relu6(v_111)
        v_113 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_depthwise_depthwise(v_112)
        v_114 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_depthwise_relu_Relu6(v_113)
        v_115 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_block_16_project_Conv2D(v_114)
        v_116 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_Conv_1_Conv2D(v_115)
        v_117 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_functional_1_out_relu_Relu6(v_116)
        v_118 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_2_1x1_256_conv_Conv2D(v_117)
        v_119 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_1_ClassPredictor_BiasAdd(v_117)
        v_120 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_1_BoxEncodingPredictor_BiasAdd(v_117)
        v_121 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_2_1x1_256_Relu6(v_118)
        v_122 = v_119.permute(dims=(0,2,3,1))
        v_123 = v_120.permute(dims=(0,2,3,1))
        v_124 = F.pad(v_121, mode='constant', pad=(0,1,0,1), value=0.0)
        v_125 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_2_3x3_s2_512_conv_Conv2D_1(v_124)
        v_126 = v_122.reshape(1, 600, 91)
        v_127 = v_123.reshape(1, 600, 1, 4)
        v_128 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_2_3x3_s2_512_Relu6(v_125)
        v_129 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_3_1x1_128_conv_Conv2D(v_128)
        v_130 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_2_ClassPredictor_BiasAdd(v_128)
        v_131 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_2_BoxEncodingPredictor_BiasAdd(v_128)
        v_132 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_3_1x1_128_Relu6(v_129)
        v_133 = v_130.permute(dims=(0,2,3,1))
        v_134 = v_131.permute(dims=(0,2,3,1))
        v_135 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_3_3x3_s2_256_conv_Conv2D(v_132)
        v_136 = v_133.reshape(1, 150, 91)
        v_137 = v_134.reshape(1, 150, 1, 4)
        v_138 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_3_3x3_s2_256_Relu6(v_135)
        v_139 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_4_1x1_128_conv_Conv2D(v_138)
        v_140 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_3_ClassPredictor_BiasAdd(v_138)
        v_141 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_3_BoxEncodingPredictor_BiasAdd(v_138)
        v_142 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_4_1x1_128_Relu6(v_139)
        v_143 = v_140.permute(dims=(0,2,3,1))
        v_144 = v_141.permute(dims=(0,2,3,1))
        v_145 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_4_3x3_s2_256_conv_Conv2D(v_142)
        v_146 = v_143.reshape(1, 54, 91)
        v_147 = v_144.reshape(1, 54, 1, 4)
        v_148 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_4_3x3_s2_256_Relu6(v_145)
        v_149 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_5_1x1_64_conv_Conv2D(v_148)
        v_150 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_4_ClassPredictor_BiasAdd(v_148)
        v_151 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_4_BoxEncodingPredictor_BiasAdd(v_148)
        v_152 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_1_Conv2d_5_1x1_64_Relu6(v_149)
        v_153 = v_150.permute(dims=(0,2,3,1))
        v_154 = v_151.permute(dims=(0,2,3,1))
        v_155 = F.pad(v_152, mode='constant', pad=(0,1,0,1), value=0.0)
        v_156 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_conv_Conv2D_1(v_155)
        v_157 = v_153.reshape(1, 24, 91)
        v_158 = v_154.reshape(1, 24, 1, 4)
        v_159 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_batchnorm_FusedBatchNormV3(v_156)
        v_160 = self.core_StatefulPartitionedCall_ssd_mobile_net_v2keras_feature_extractor_FeatureMaps_layer_19_2_Conv2d_5_3x3_s2_128_Relu6(v_159)
        v_161 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalClassHead_5_ClassPredictor_BiasAdd(v_160)
        v_162 = self.core_StatefulPartitionedCall_BoxPredictor_ConvolutionalBoxHead_5_BoxEncodingPredictor_BiasAdd(v_160)
        v_163 = v_161.reshape(1, 6, 91)
        v_164 = v_162.reshape(1, 6, 1, 4)
        v_165 = torch.cat((v_97, v_126, v_136, v_146, v_157, v_163), dim=1)
        v_166 = torch.cat((v_98, v_127, v_137, v_147, v_158, v_164), dim=1)
        v_167 = self.core_StatefulPartitionedCall_Postprocessor_convert_scores(v_165)
        v_168 = v_166.reshape(1917, 4)
        v_169 = v_168.permute(dims=(1,0))
        v_170, v_171, v_172, v_173 = torch.split(tensor=v_169, dim=0, split_size_or_sections=1)
        v_174 = torch.squeeze(v_173, dim=0)
        v_175 = torch.squeeze(v_172, dim=0)
        v_176 = torch.squeeze(v_171, dim=0)
        v_177 = torch.squeeze(v_170, dim=0)
        v_178 = ((v_176 * v_7) + v_5)
        v_179 = ((v_177 * v_6) + v_4)
        v_180 = ((torch.exp((v_174 * 0.2)) * v_3) * 0.5)
        v_181 = ((torch.exp((v_175 * 0.2)) * v_2) * 0.5)
        v_182 = (v_178 - v_180)
        v_183 = (v_178 + v_180)
        v_184 = (v_179 - v_181)
        v_185 = (v_179 + v_181)
        v_186 = v_182.unsqueeze(0)
        v_187 = v_183.unsqueeze(0)
        v_188 = v_184.unsqueeze(0)
        v_189 = v_185.unsqueeze(0)
        v_190 = torch.cat((v_188, v_186, v_189, v_187), dim=0)
        v_191 = v_190.permute(dims=(1,0))
        v_192 = v_191.reshape(1, 1917, 4)
        v_193 = [v_192, v_167]
        return v_193

def export_torchscript():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 3, 320, 320, dtype=torch.float)

    mod = torch.jit.trace(net, v_0)
    mod.save("ssd_try_pnnx_pnnx.py.pt")

def export_onnx():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 3, 320, 320, dtype=torch.float)

    torch.onnx.export(net, v_0, "ssd_try_pnnx_pnnx.py.onnx", export_params=True, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, opset_version=13, input_names=['in0'], output_names=['out0'])

def export_pnnx():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 3, 320, 320, dtype=torch.float)

    import pnnx
    pnnx.export(net, "ssd_try_pnnx_pnnx.py.pt", v_0)

def export_ncnn():
    export_pnnx()

@torch.no_grad()
def test_inference():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 3, 320, 320, dtype=torch.float)

    return net(v_0)

if __name__ == "__main__":
    print(test_inference())
